# This file was generated by GoReleaser. DO NOT EDIT.
cask "weft" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7dc9e978cbf743ad5e7f69cf38b24d94db2200f8eaa8b04494a99b3b43f02767"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "958562c9c3ca1b8446216279aa518bd471b850e31b54aad36b552b9de29c61fa"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d512593b80246933b680cfeb4549626ae57967a56f5c7e23d4cadef3cd43b85"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "32f15d0691d898daf582d01a911ef69d511b5874d29f028c2f752bf5219aa01f"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_linux_arm64.tar.gz"
    end
  end

  name "weft"
  desc "Composable AI rules manager for coding agents and harnesses"
  homepage "https://github.com/jophira/weft-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weft"

  # No zap stanza required

end
