# This file was generated by GoReleaser. DO NOT EDIT.
cask "weft" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "1960b92cea82faf7fdab697a644223961d80ef7dd8c0c7e0dac442a53b5d108b"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "445162e8815c11803567372be0bc103227ed8a33cc5d1af15574a8130ca64799"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "415f13c28708f351ff9c46c62e0ebf59ed1304cd907d4a3f8fb9c889762c1ed5"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "92eeac3ddbdb323fd6abdb857d5009882ba4547f7452aede52e75345247454b5"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_linux_arm64.tar.gz"
    end
  end

  name "weft"
  desc "weft — a tool for managing git source sync and hooks"
  homepage "https://github.com/jophira/weft-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weft"

  # No zap stanza required

end
