# This file was generated by GoReleaser. DO NOT EDIT.
cask "weft" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "228c17e581c56bd604723d1e4f5ec739bac0c65432a5df749b287484850481ab"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "da6c8613fd277ff95848596162f3e16be217fad04d684ff22f4b0e092a6a28ce"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b75fa9626473c1b96d36ddd6a24db1299ea8586e0483a1d8a11c7be635cdb0c7"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a20017d38fc9001ff74ea9528be7bf9999e952ff80b436c7bbdc204c4920691"
      url "https://github.com/jophira/weft-releases/releases/download/v#{version}/weft_linux_arm64.tar.gz"
    end
  end

  name "weft"
  desc "weft — a tool for managing git source sync and hooks"
  homepage "https://github.com/jophira/weft-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weft"

  # No zap stanza required

end
